name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Print trigger information
        run: echo "* The job was automatically triggered by a ${GITHUB_EVENT_NAME} event."
      
      - name: Print runner information
        run: echo "This job is now running on a ${{ runner.os }} runner."
      
      - name: Print branch information
        run: echo "The name of your branch is ${GITHUB_REF}."
      
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Print repository information
        run: echo "The ${{ github.repository }} repository has been checked out."

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      - name: Print job status
        run: echo "* This job's status is ${{ job.status }}."
